www := "/var/www/organizator.ro"

build:
  reset
  npm run build
  cp favicon-green.ico build/main/favicon.ico

install-dependencies:
  npm update
  npm install
  npm install typescript --save-dev

deploy: build
  cp src/html/* {{www}}
  cp -r build/main/dom/ {{www}}

