build:
  wasm-pack build --target web

deploy: build
  rsync -av pkg/ /var/www/organizator.ro/pkg/

install:
  cargo install wasm-pack

test:
  cargo test test_process_markdown -- --nocapture
  #cargo test markdown::test::test_process_markdown -- --nocapture

test-checkbox:
  cargo test test_process_checkbox -- --nocapture

