FROM bitnami/minideb:stretch

COPY . .
CMD ["./hyper-organizator"]
EXPOSE 3000

LABEL maintainer="Ovidiu Ionescu <ovidiu@ionescu.net>" \
  version="0.2" \
  description="Web service implemented with Hyper" \
  repository="https://github.com/ovidiu-ionescu/organizator-3" \
  name="hyper-organizator"

