apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hyper-organizator-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: k8s.organizator.ro
      http:
        paths:
          - path: /(|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: hyper-organizator
                port:
                  number: 80
