apiVersion: v1
kind: ConfigMap
metadata: 
  namespace: organizator-dev 
  name: hyper-organizator-config
  annotations:
    description: "Configuration for hyper-organizator"
data:
  settings.toml: |-
    api_ip = "0.0.0.0:8080"
    metrics_ip = "0.0.0.0:8081"
  rust_log_level: INFO

