[package]
name = "lib-axum-organizator"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2.workspace = true
axum.workspace = true
base64.workspace = true
deadpool-postgres.workspace = true
dirs.workspace = true
indoc.workspace = true
jsonwebtoken.workspace = true
mimalloc.workspace = true
reqwest.workspace = true
ring.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
utoipa.workspace = true
