api_ip = "0.0.0.0:8082"
metrics_ip = "0.0.0.0:3002"
swagger_path = "/swagger"

[postgres]
host = "orgdb.lab"
port = 5432
user = "organizator_prod"
dbname = "organizator_prod"
# password comes from the environment variable POSTGRES_PASSWORD

[security]
public_key_url = "http://localhost:8080/public"
ignore = [ 
"/public",
"/swagger",
"/swagger/api-doc.json",
]

[file_storage]
# file storage directory
path = "../../../Frontend/Nginx/files"
