-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated 
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps. 
 BEGIN; 
 ALTER TABLE IF EXISTS public.users
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.users
    FORCE ROW LEVEL SECURITY;

ALTER TABLE public.users
    ALTER COLUMN password TYPE text COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS public.users
    ADD COLUMN password_hash text COLLATE pg_catalog."default";

CREATE POLICY update_policy
    ON public.users
    AS PERMISSIVE
    FOR UPDATE
    TO public
    USING ((((current_setting('organizator.current_user'::text))::integer = id) OR ((current_setting('organizator.current_user'::text))::integer = 1)));


CREATE POLICY select_policy
    ON public.users
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);

ALTER TABLE IF EXISTS public.memo
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.memo
    FORCE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.memo
    ALTER COLUMN title SET NOT NULL;

ALTER TABLE IF EXISTS public.memo
    ALTER COLUMN memotext SET NOT NULL;
ALTER TABLE IF EXISTS public.memo
    ADD CONSTRAINT memo_group_foreign_key FOREIGN KEY (group_id)
    REFERENCES public.memo_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_memo_group_foreign_key
    ON public.memo USING btree
    (group_id ASC NULLS LAST)
    TABLESPACE pg_default;


CREATE POLICY user_policy
    ON public.memo
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((((current_setting('organizator.current_user'::text))::integer = user_id) OR ((current_setting('organizator.current_user'::text))::integer = 0) OR ((current_setting('organizator.current_user'::text))::integer IN ( SELECT user_group_detail.user_id
   FROM memo_acl,
    user_group_detail
  WHERE ((memo_acl.memo_group_id = memo.group_id) AND (memo_acl.access > 0) AND (user_group_detail.user_group_id = memo_acl.user_group_id))))));


CREATE POLICY update_policy_owner
    ON public.memo
    AS PERMISSIVE
    FOR UPDATE
    TO public
    USING ((user_id = (current_setting('organizator.current_user'::text))::integer));

CREATE OR REPLACE FUNCTION public.set_current_user(
	p_username character varying,
	OUT o_user_id integer)
    RETURNS integer
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
DECLARE
    --o_user_id users.id%TYPE;
BEGIN
    BEGIN
    -- Look up the user's ID in the users table
    SELECT users.id INTO STRICT o_user_id FROM users WHERE users.username = p_username;
    EXCEPTION 
      WHEN NO_DATA_FOUND THEN
        RAISE EXCEPTION 'user % not found', p_username USING ERRCODE = '28000'; -- invalid_authorization_specification
      WHEN TOO_MANY_ROWS THEN
        RAISE EXCEPTION 'fetched more than one user for %', p_username USING ERRCODE = '28000'; -- invalid_authorization_specification
    END;
	--o_username := p_username;
    
    -- Set the session variable
    PERFORM set_config('organizator.current_user', o_user_id::TEXT, false);
END;
$BODY$;

ALTER FUNCTION public.set_current_user(character varying)
    OWNER TO myuser;


 END;