name: Build and Deploy mdBook

on:
  push:
    branches:
      - master  # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install mdBook
        run: cargo install mdbook

      - name: Build mdBook
        run: mdbook build Doc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Doc/book

